##
## EPITECH PROJECT, 2019
## Makefile
## File description:
## root Makefile
##

all:
	cd asm && $(MAKE)
	cd vm && $(MAKE)

clean:
	cd asm && $(MAKE) clean
	cd vm && $(MAKE) clean

fclean:
	cd asm && $(MAKE) fclean
	cd vm && $(MAKE) fclean

re: fclean all